"""Initial schema

Revision ID: 349d41b81b07
Revises: 
Create Date: 2026-10-07 00:07:36.861852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349d41b81b07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_a_id', sa.String(), nullable=False),
    sa.Column('dataset_b_id', sa.String(), nullable=False),
    sa.Column('mapping_config', sa.JSON(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_a_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['dataset_b_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('match_pairs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('record_a_id', sa.String(), nullable=False),
    sa.Column('record_b_id', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_pairs_id'), 'match_pairs', ['id'], unique=False)
    op.create_index(op.f('ix_match_pairs_job_id'), 'match_pairs', ['job_id'], unique=False)
    op.create_index(op.f('ix_match_pairs_record_a_id'), 'match_pairs', ['record_a_id'], unique=False)
    op.create_index(op.f('ix_match_pairs_record_b_id'), 'match_pairs', ['record_b_id'], unique=False)
    op.create_table('review_labels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pair_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['match_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_labels_id'), 'review_labels', ['id'], unique=False)
    op.create_index(op.f('ix_review_labels_pair_id'), 'review_labels', ['pair_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_labels_pair_id'), table_name='review_labels')
    op.drop_index(op.f('ix_review_labels_id'), table_name='review_labels')
    op.drop_table('review_labels')
    op.drop_index(op.f('ix_match_pairs_record_b_id'), table_name='match_pairs')
    op.drop_index(op.f('ix_match_pairs_record_a_id'), table_name='match_pairs')
    op.drop_index(op.f('ix_match_pairs_job_id'), table_name='match_pairs')
    op.drop_index(op.f('ix_match_pairs_id'), table_name='match_pairs')
    op.drop_table('match_pairs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
